version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # We only need to install dependencies.
      # The build happens inside the 'api' folder.
      - cd api
      - npm install --production

artifacts:
  # This tells CodePipeline what to package for deployment.
  # It's the most important part.
  base-directory: 'api'
  files:
    # This glob pattern means "include all files and all folders recursively"
    # from within the 'base-directory'.
    - '**/*'