version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      # Step 1: Make the build script executable
      - chmod +x build.sh
      # Step 2: Run the build script
      - ./build.sh

artifacts:
  # The artifacts are created by the build.sh script
  files:
    - node_api_package.zip
    - imagedefinitions.json
  discard-paths: yes